spring.application.name=dinamika_back
ip_address=http://109.69.22.155

# База данных PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/dinamika?useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=postgres
spring.datasource.password=Tuduta95

# JPA настройки - ВРЕМЕННО create
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway настройки (явные)
spring.flyway.url=jdbc:postgresql://localhost:5432/dinamika
spring.flyway.user=postgres
spring.flyway.password=Tuduta95
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.enabled=true

# Отключаем стандартную инициализацию
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false

# Остальные настройки
server.port=8084
server.address=0.0.0.0
logging.level.com.example=DEBUG
logging.level.org.flywaydb=DEBUG

jwt.cookie-token-key={"kty":"oct","kid":"d23af0bb-9ed5-4ae8-9026-82c206c9865b","k":"mVN0Rvq0jSGa09hhKGd4fQ","alg":"A128GCM"}
jwt.access-token-name=access-token
jwt.access-token-expiration-minutes=180
jwt.refresh-token-name=refresh-token
jwt.refresh-token-expiration-minutes=14400

file.upload-dir=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true

sync.service.url=http://localhost:8085